file_format: "1"
id: pandaboard
name: Pandaboard
type: shield
url: https://github.com/jakecoates/zmk-config/
requires: [pro_micro]
features:
  - keys
  - Mouse keys pointer
  - Trackball pointer
  - Dongle/Bluetooth/USB
siblings:
  - pandaboard_left
  - pandaboard_right